module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: null
cabal-file: project.cabal
modules:
  Lesson02:
    filename: src/Lesson02.hs
  Helper:
    filename: src/Helper.hs
  Lesson01:
    filename: src/Lesson01.hs
version: 1
ghc-args: []
