module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: null
cabal-file: project.cabal
modules:
  Lesson04:
    filename: src/Lesson04.hs
  Lesson02:
    filename: src/Lesson02.hs
  Lesson05:
    filename: src/Lesson05.hs
  Lesson08:
    filename: src/Lesson08.hs
  Lesson03:
    filename: src/Lesson03.hs
  Helper.WinningTests:
    filename: src/Helper/WinningTests.hs
  Helper:
    filename: src/Helper.hs
  Lesson06:
    filename: src/Lesson06.hs
  Lesson07:
    filename: src/Lesson07.hs
  Helper.Multiplayer:
    filename: src/Helper/Multiplayer.hs
  Helper.Winning:
    filename: src/Helper/Winning.hs
  Helper.Pretty:
    filename: src/Helper/Pretty.hs
  Lesson01:
    filename: src/Lesson01.hs
version: 1
ghc-args: []
